import { Theme } from '@mui/material/styles';

export const styles = {
    container: () => (theme: Theme) => ({
        minHeight: '100vh',
        backgroundColor: theme.palette.background.default,
        padding: theme.spacing(4),
        maxWidth: 1400,
        margin: '0 auto',
    }),
    header: () => (theme: Theme) => ({
        marginBottom: theme.spacing(4),
    }),
    title: () => (theme: Theme) => ({
        color: theme.palette.text.primary,
        fontWeight: 600,
        marginBottom: theme.spacing(0.5),
        letterSpacing: '-0.02em',
    }),
    subtitle: () => (theme: Theme) => ({
        color: theme.palette.text.secondary,
        fontSize: '0.9375rem',
    }),
    metricsGrid: () => (theme: Theme) => ({
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
        gap: theme.spacing(2),
        marginBottom: theme.spacing(4),
    }),
    metricCard: () => (theme: Theme) => ({
        backgroundColor: theme.palette.background.paper,
        borderRadius: 4,
        padding: theme.spacing(2.5),
        border: '1px solid rgba(148, 163, 184, 0.12)',
        transition: 'all 0.2s ease',
        '&:hover': {
            borderColor: 'rgba(59, 130, 246, 0.3)',
            boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
        },
    }),
    metricLabel: () => (theme: Theme) => ({
        color: theme.palette.text.secondary,
        fontSize: '0.875rem',
        marginBottom: theme.spacing(0.5),
        fontWeight: 500,
    }),
    metricValue: () => (theme: Theme) => ({
        color: theme.palette.text.primary,
        fontSize: '1.75rem',
        fontWeight: 600,
        lineHeight: 1.2,
    }),
    contentGrid: () => (theme: Theme) => ({
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(400px, 1fr))',
        gap: theme.spacing(3),
        marginBottom: theme.spacing(3),
    }),
    sectionCard: () => (theme: Theme) => ({
        backgroundColor: theme.palette.background.paper,
        borderRadius: 4,
        padding: theme.spacing(3),
        border: '1px solid rgba(148, 163, 184, 0.12)',
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
    }),
    sectionHeader: () => (theme: Theme) => ({
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: theme.spacing(2),
    }),
    sectionTitle: () => (theme: Theme) => ({
        color: theme.palette.text.primary,
        fontWeight: 600,
        fontSize: '1.125rem',
    }),
    sectionContent: () => () => ({
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        gap: 1,
    }),
    emptyState: () => (theme: Theme) => ({
        textAlign: 'center',
        padding: theme.spacing(4, 2),
        color: theme.palette.text.secondary,
        fontSize: '0.875rem',
    }),
    actionItem: () => (theme: Theme) => ({
        padding: theme.spacing(1.5),
        borderRadius: 4,
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        border: '1px solid transparent',
        '&:hover': {
            backgroundColor: 'rgba(59, 130, 246, 0.08)',
            borderColor: 'rgba(59, 130, 246, 0.2)',
        },
    }),
    actionTitle: () => (theme: Theme) => ({
        color: theme.palette.text.primary,
        fontWeight: 500,
        fontSize: '0.9375rem',
        marginBottom: theme.spacing(0.5),
    }),
    actionMeta: () => (theme: Theme) => ({
        color: theme.palette.text.secondary,
        fontSize: '0.8125rem',
        display: 'flex',
        alignItems: 'center',
        gap: theme.spacing(1),
    }),
    priorityBadge: (priority: 'high' | 'medium' | 'low') => (theme: Theme) => ({
        display: 'inline-block',
        padding: '2px 8px',
        borderRadius: 4,
        fontSize: '0.75rem',
        fontWeight: 500,
        ...(priority === 'high' && {
            backgroundColor: 'rgba(248, 113, 113, 0.15)',
            color: '#FCA5A5',
        }),
        ...(priority === 'medium' && {
            backgroundColor: 'rgba(251, 191, 36, 0.15)',
            color: '#FCD34D',
        }),
        ...(priority === 'low' && {
            backgroundColor: 'rgba(148, 163, 184, 0.15)',
            color: 'rgba(203, 213, 225, 0.8)',
        }),
    }),
    messageItem: () => (theme: Theme) => ({
        padding: theme.spacing(1.5),
        borderRadius: 4,
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        border: '1px solid transparent',
        '&:hover': {
            backgroundColor: 'rgba(59, 130, 246, 0.08)',
            borderColor: 'rgba(59, 130, 246, 0.2)',
        },
    }),
    messageHeader: () => (theme: Theme) => ({
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: theme.spacing(0.5),
    }),
    messageContact: () => (theme: Theme) => ({
        color: theme.palette.text.primary,
        fontWeight: 500,
        fontSize: '0.9375rem',
    }),
    messageTime: () => (theme: Theme) => ({
        color: theme.palette.text.secondary,
        fontSize: '0.75rem',
    }),
    messageSnippet: () => (theme: Theme) => ({
        color: theme.palette.text.secondary,
        fontSize: '0.8125rem',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
    }),
    outOfSyncBadge: () => () => ({
        display: 'inline-block',
        padding: '2px 6px',
        borderRadius: 4,
        fontSize: '0.75rem',
        fontWeight: 500,
        backgroundColor: 'rgba(251, 191, 36, 0.15)',
        color: '#FCD34D',
        marginTop: 4,
    }),
    overdueItem: () => (theme: Theme) => ({
        padding: theme.spacing(1.5),
        borderRadius: 4,
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        border: '1px solid rgba(248, 113, 113, 0.2)',
        backgroundColor: 'rgba(248, 113, 113, 0.05)',
        '&:hover': {
            backgroundColor: 'rgba(248, 113, 113, 0.1)',
            borderColor: 'rgba(248, 113, 113, 0.3)',
        },
    }),
    overdueBadge: () => () => ({
        display: 'inline-block',
        padding: '2px 8px',
        borderRadius: 4,
        fontSize: '0.75rem',
        fontWeight: 500,
        backgroundColor: 'rgba(248, 113, 113, 0.15)',
        color: '#FCA5A5',
        marginLeft: 8,
    }),
    loadingContainer: () => (theme: Theme) => ({
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 400,
        padding: theme.spacing(4),
    }),
    errorContainer: () => (theme: Theme) => ({
        padding: theme.spacing(3),
        marginBottom: theme.spacing(3),
    }),
};
